site_name: Kangaroo Site
nav:
    - Home: index.md
    - 源码阅读笔记: 
      - Megatron:
        - create_masked_lm_predictions.md
        - pad_and_convert_to_numpy.md
        - GPTDataset.md
theme: 
  name: material
  features:
    - navigation.tracking
    - navigation.tabs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 